services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage
    ports:
        - 9898:5432
    volumes:
      - backstage-postgres:/var/lib/postgresql/data

volumes:
    backstage-postgres: